# Generated by Django 4.2.5 on 2023-09-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShorterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=4096, unique=True)),
                ('hits', models.PositiveIntegerField(verbose_name=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['long_url'], name='shorter_api_long_ur_a97186_idx')],
            },
        ),
    ]
