# Generated by Django 4.2.5 on 2023-09-23 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shorter_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShorterModelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=4096, unique=True)),
                ('hits', models.PositiveIntegerField(verbose_name=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ShorterModel',
        ),
        migrations.AddIndex(
            model_name='shortermodelitem',
            index=models.Index(fields=['long_url'], name='shorter_api_long_ur_202a80_idx'),
        ),
    ]
