# Generated by Django 4.2.5 on 2023-09-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter_api', '0003_alter_shortermodelitem_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortermodelitem',
            name='hits',
            field=models.PositiveIntegerField(default='0', editable=False),
        ),
    ]
